# Generated by Django 3.1.5 on 2021-01-20 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.CharField(choices=[('C', 'Gato'), ('D', 'Cachorro'), ('H', 'Cavalo'), ('B', 'Ave'), ('O', 'Outro')], max_length=2)),
                ('birth_date', models.DateField()),
                ('description', models.TextField(max_length=5000)),
                ('size', models.CharField(choices=[('PP', 'Muito pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('G', 'Muito grande')], max_length=2)),
                ('show', models.BooleanField(default=True)),
                ('entry_date', models.DateField(auto_now_add=True)),
                ('death_date', models.DateField(blank=True, null=True)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('location', models.CharField(choices=[('C', 'Canil'), ('V', 'Voluntário')], default='C', max_length=1)),
                ('sex', models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1)),
                ('castrated', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='AnimalPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(default='default.jpeg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(choices=[('V', 'Vacina'), ('C', 'Cirurgia'), ('R', 'Remédio')], default='C', max_length=1)),
                ('information', models.TextField(max_length=1000)),
                ('date', models.DateField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='animal_operation', to='admin_animals.animal')),
            ],
        ),
    ]
