# Generated by Django 3.1.5 on 2021-01-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_animals', '0002_auto_20210117_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.CharField(choices=[('M', 'Macho'), ('F', 'Fêmea')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='animal',
            name='animal_type',
            field=models.CharField(choices=[('C', 'Gato'), ('D', 'Cachorro'), ('H', 'Cavalo'), ('B', 'Ave'), ('O', 'Outro')], max_length=2),
        ),
        migrations.AlterField(
            model_name='animal',
            name='location',
            field=models.CharField(choices=[('C', 'Canil'), ('V', 'Voluntário')], default='c', max_length=1),
        ),
    ]
