# Generated by Django 3.1.5 on 2021-01-20 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_animals', '0002_auto_20210120_1417'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
