# Generated by Django 3.1.5 on 2021-01-20 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_animals', '0003_delete_operation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='size',
            field=models.CharField(choices=[('PP', 'Muito pequeno'), ('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande'), ('GG', 'Muito grande')], max_length=2),
        ),
    ]
