# Generated by Django 3.1.5 on 2021-01-20 18:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_animals', '0003_delete_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=500)),
                ('cellphone', models.CharField(max_length=20)),
                ('adress', models.CharField(max_length=100)),
                ('document', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Adoption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adoption_date', models.DateField(auto_now_add=True)),
                ('adopter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='animal_adopter', to='adoptions.adopter')),
                ('animal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='adopted_animal', to='admin_animals.animal')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_register_adoption', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
